# Generated by Django 2.0.5 on 2018-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_key_fp', models.CharField(max_length=64)),
                ('kh_msg_text', models.CharField(max_length=1024)),
                ('kh_msg_timestamp', models.DateTimeField()),
                ('lockee_msg_text', models.CharField(max_length=1024)),
                ('lockee_msg_timestamp', models.DateTimeField()),
                ('locked', models.BooleanField()),
                ('unlock_time', models.DateTimeField()),
            ],
        ),
    ]
