# Generated by Django 2.0.5 on 2018-07-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0002_auto_20180728_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='proximityunit',
            field=models.CharField(default='H', max_length=1),
        ),
    ]
