# Generated by Django 2.0.5 on 2018-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_auto_20180728_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattributes',
            name='displayname',
            field=models.CharField(default='Hants_Masters', max_length=30),
            preserve_default=False,
        ),
    ]
