# Generated by Django 2.0.5 on 2018-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0004_userattributes_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='keyholder_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='keyholder_msg_timestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='safeholder_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='safeholder_msg_timestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='seen_by_safeholder',
            field=models.DateTimeField(blank=True),
        ),
    ]
