# Generated by Django 2.0.5 on 2018-07-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0005_auto_20180728_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='keyholder_msg_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='safeholder_msg_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
