# Generated by Django 2.0.5 on 2018-07-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0006_auto_20180728_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='keyholder_msg_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='safeholder_msg_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='seen_by_safeholder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
