# Generated by Django 2.0.5 on 2018-07-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0007_auto_20180728_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Safe_Events',
            new_name='Safe_Event',
        ),
    ]
