# Generated by Django 2.0.5 on 2018-07-31 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0008_auto_20180728_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='reportfreq',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='safe',
            name='safeholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safe',
            name='scanfreq',
            field=models.IntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name='safe',
            name='unlock_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
