# Generated by Django 2.0.5 on 2018-08-12 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safe', '0009_auto_20180731_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='keyholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kh_safes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safe',
            name='keyholder_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='keyholder_msg_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='relationship_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='safeholder_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='safeholder_msg_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='seen_by_safeholder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safe',
            name='safeholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sh_safes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safe_event',
            name='safe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='safe.Safe'),
        ),
    ]
