# Generated by Django 2.0.5 on 2018-08-12 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0010_auto_20180812_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='keyholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kh_safes', to=settings.AUTH_USER_MODEL),
        ),
    ]
