# Generated by Django 2.0.5 on 2018-08-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0011_auto_20180812_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='proximityunit',
            field=models.CharField(choices=[('M', 'Minutes'), ('H', 'Hours'), ('D', 'Days'), ('W', 'Weeks')], default='H', max_length=1),
        ),
    ]
