# Generated by Django 2.0.5 on 2018-08-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0013_auto_20180813_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='auth_to_unlock',
            field=models.BooleanField(default=False, verbose_name='Authorised to unlock'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='displayproximity',
            field=models.BooleanField(default=True, verbose_name='Display proximity lights'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='keyholder_msg',
            field=models.TextField(blank=True, verbose_name='Message from Key holder'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='last_update',
            field=models.DateTimeField(verbose_name='Last update from safe'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='proximityunit',
            field=models.CharField(choices=[('M', 'Minutes'), ('H', 'Hours'), ('D', 'Days'), ('W', 'Weeks')], default='H', max_length=1, verbose_name='Safe lights show proximity to unlock in:'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='relationship_active',
            field=models.BooleanField(default=True, verbose_name='Is the relationship active'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='reportfreq',
            field=models.IntegerField(default=1, verbose_name='Reporting Frequency (numebr of scan periods)'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='safeholder_msg',
            field=models.TextField(blank=True, verbose_name='Message from safe holder'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='unlock_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time to unlock'),
        ),
    ]
