# Generated by Django 2.1.11 on 2019-08-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0015_auto_20190226_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='safeholder_key',
            field=models.CharField(default='NONE', max_length=36, verbose_name="Safeholder's key"),
        ),
    ]
